title: Portfolio - Tiago Sabadini
author:
  name: Tiago Sabadini
  typeItems: Programador, Gestor de Projetos, CTO
  twitter: "https://twitter.com/tiagosabadini"
  facebook: "https://facebook.com/tiagosabadini"
  instagram: "https://instagram.com/tiagosabadini"
  linkedin: "https://linkedin.com/tiagosabadini"

sessoes:
  sobre:
    titulo: "Sobre mim"
    foto: "assets/img/profile-img.jpg"
    descricao: "Graduação em Analise e Desenvolvimento de sistemas, MBAs em Gestão de Projetos e Gestão Exponencial e Empreendedorismo. <br/>
            Tenho mais de 10 anos de experiência como programador. Iniciando em agências de publicidade com wordpress e criação de layouts para sites.<br/>       
            Criei minha primeira empresa para desenvolvimento de sites em 2010. Em 2014 fundei uma software house com um sócio e prestamos serviços para setor financeiro em todo Brasil. Fiz meu primeiro exit em 2019 vendendo minha participação na empresa."
    tituloProfissional: "CTO at BYeCAR"
    descricaoProfissional: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore
              magna aliqua."
    dataNascimento: "06/12/1983"
    website: "https://blog.itgolabs.com"
    whatsapp: "(27) 9 0000-0000"
    cidade: "Vitória"
    idade: 39
    email: "sabadini.tiago@gmail.com"
    graduacao: "MBA em Gestão Exponencial"
    freelance: "Disponível"

  experiencia:
    titulo: "Experiência"
    descricao: "Magnam dolores commodi suscipit. Necessitatibus eius consequatur ex aliquid fuga eum quidem. Sit sint consectetur velit. Quisquam quos quisquam cupiditate. Et nemo qui impedit suscipit alias ea. Quia fugiat sit in iste officiis commodi quidem hic quas."
    
    tituloSumario: "Tiago Sabadini"
    descricaoSumario: "Innovative and deadline-driven Graphic Designer with 3+ years of experience designing and developing user-centered digital/print marketing material from initial concept to final, polished deliverable."
    detalheSumario:
      - "Portland par 127,Orlando, FL"
      - "(123) 456-7891"
      - "alice.barkley@example.com"

    educacao:
      - 
        titulo: "Master of Fine Arts &amp; Graphic Design"
        ano: "2015 - 2016"
        instituicao: "Rochester Institute of Technology, Rochester, NY"
        descricao: "Qui deserunt veniam. Et sed aliquam labore tempore sed quisquam iusto autem sit. Ea vero voluptatum qui ut dignissimos deleniti nerada porti sand markend"
      
      -
        titulo: "Bachelor of Fine Arts &amp; Graphic Design"
        ano: "2010 - 2014"
        instituicao: "Rochester Institute of Technology, Rochester, NY"
        descricao: "Qui deserunt veniam. Et sed aliquam labore tempore sed quisquam iusto autem sit. Ea vero voluptatum qui ut dignissimos deleniti nerada porti sand markend"
    
    historicoProfissional:
      - 
        titulo: "Senior graphic design specialist"
        ano: "2019 - Present"
        instituicao: "Experion, New York, NY"
        atividades:
          - "Lead in the design, development, and implementation of the graphic, layout, and production communication materials"
          - "Delegate tasks to the 7 members of the design team and provide counsel on all aspects of the project."
          - "Supervise the assessment of all graphic materials in order to ensure quality and accuracy of the design"
      
      -
        titulo: "Graphic design specialist"
        ano: "2017 - 2018"
        instituicao: "Stepping Stone Advertising, New York, NY"
        atividades:
          - "Developed numerous marketing programs (logos, brochures,infographics, presentations, and advertisements)."
          - "Managed up to 5 projects or tasks at a given time while under pressure"
          - "Recommended and consulted with clients on the most appropriate graphic design"


    