title: Portfolio - Tiago Sabadini
author:
  name: Tiago Sabadini
  typeItems: Programador, Gestor de Projetos, CTO
  twitter: "https://twitter.com/tiagosabadini"
  facebook: "https://facebook.com/tiagosabadini"
  instagram: "https://instagram.com/tiagosabadini"
  linkedin: "https://linkedin.com/tiagosabadini"